travis:
  secure:
    BINSTAR_TOKEN: r3o01yWcM5tfoJNH5Kcx7CB0KJDMJfBSJx9/r9xUYQxqVCOnn6UZr1xDJieSlmjRJiRUnBVjMIB/LjGMk5K+o7WX4nRMOh3ADdx+muoNSwoI2tSa629UfT4lLqtfMbg9PAkz3B29bd88ODyIVjEH5V3Ky2wbjGFdtOwoQene78BbaLy50IhcPSdF7pfc1spH/v8fQSwhg/qIXn+IFRwuAwSjeQUIayrjfDhKBY316PMH5ru9bdYEeEVg7kOarxquOnm3aBINabiSUTPNFiLwYh1dTqr+RxZW2w9Hdfv0D3HUzbjviYtX3lyCULtUmnH4dpc05Zg9VDkTkMu2HSTr+kG44oDia6aegDuU84iqtOQkDlAG9DhIzYFuq1IjhkdvV05SojySqu3K3K2E0SS/9/LFTcnxvhDu40EFpTWhEUK+ve3tTjaFqSbXp1fZ6oJAgCVMHAI50xBj9orbvfW4Euq9qH7QqRvQ+sKOuFAWt8QERRimq+7PH3+ragvs4pRMjobopgzZ2NCwy3Mo7drCGkFr8koqD0kfi7z0GQ+XlzuQVBI9AZajenN9Ny3IsNTgqG67K/h5wH63pxhAhe+EyVnIonoqM4Sh4uOomCb3s6ejtH2q9A7BUr7k2nVZ2CW5fI8XJ58bAfMnsTsKTNiS7PNS5PKZTKxRtQcC3Bdsdsc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
